### ISSUE TITLE
@Roey-coding @ivkin25 To understand if we start over or commit this changes + @AmitTPB

### ISSUE THREAD

**Issue by revirtux** [revirtux/BetaSeferSite#22]
@Roey-coding @ivkin25 To understand if we start over or commit this changes + @AmitTPB

_Originally posted by @revirtux in https://github.com/revirtux/BetaSeferSite/issues/21#issuecomment-766089430_

**Comment by ivkin25** [comment]
After the discussion between the scraper team, we took a decision to ditch the current [user profile branch](https://github.com/revirtux/BetaSeferSite/tree/user-profile) and redo the mission.

According to the scraper team, the database's API offers functions for most of the mission's needs, for example, retrieving users' houses, the challenges they have solved, and more, and if a requested function does not exist, it is the scraper team's responsibility to update/extend the API accordingly.
