### ISSUE TITLE
Remove the "Challenges Resources" from the challenges category

### ISSUE THREAD

**Issue by revirtux** [revirtux/BetaSeferSite#32]

**Comment by itayboop** [comment]
אחרי בדיקה זה לא נראה כאילו זה עובר עליו.

**Comment by itayboop** [comment]
![image](https://user-images.githubusercontent.com/62623082/105721612-72da2c80-5f2d-11eb-97b7-d99603b661ee.png)

You can see the list of challenges title which we include
