### ISSUE TITLE
לאסוף תמונות מתאימות לבאנרים של הקטגוריות

### ISSUE THREAD

**Issue by revirtux** [revirtux/BetaSeferSite#5]
שימושים:
1. באנר בראש העמוד של הקטגוריה (ראה דוגמאת הדף של mallory)
2. בכרטיסים בתחתית העמוד הראשי כתמונת רקע

**Comment by Roey-coding** [comment]
Results:

[results.zip](https://github.com/revirtux/BetaSeferSite/files/5896194/final.zip)

**Comment by AmitTPB** [comment]
> 
> 
> Results:
> 
> [results.zip](https://github.com/revirtux/BetaSeferSite/files/5896194/final.zip)

Looks good.
